### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by kyoheiShibata-mini** [kyoheiShibata-mini/furima_28693#8]
- アプリURL
https://furima-28693.herokuapp.com/
- Basic認証のIDとパスワード
user:admin
password:2222
- 出品者用のメールアドレスとパスワード
mail:bob@bob
password:bob0000
- 購入者用のメールアドレスとパスワード
mail:sum@sum
password:sum0000
- 購入用カードの番号・期限・セキュリティコード
card:4242424242424242
exp_date:1 23
cvc:123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。

**Comment by kyoheiShibata-mini** [comment]
ありがとうございます！
